/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

/**
 *
 * @author karlo
 */
public class ingresoUI extends javax.swing.JPanel {

    /**
     * Creates new form ingresoUI
     */
    public ingresoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        southBody = new javax.swing.JPanel();
        panel_btn1 = new componentes.panel_btn();
        panel_btn2 = new componentes.panel_btn();
        panel_btn3 = new componentes.panel_btn();
        northBody = new javax.swing.JPanel();
        down = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        up.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel1.setText("jLabel1");
        up.add(jLabel1);

        add(up, java.awt.BorderLayout.NORTH);

        body.setLayout(new java.awt.BorderLayout());

        southBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        southBody.add(panel_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        southBody.add(panel_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        southBody.add(panel_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        body.add(southBody, java.awt.BorderLayout.CENTER);
        body.add(northBody, java.awt.BorderLayout.PAGE_START);

        add(body, java.awt.BorderLayout.CENTER);
        add(down, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel down;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel northBody;
    private componentes.panel_btn panel_btn1;
    private componentes.panel_btn panel_btn2;
    private componentes.panel_btn panel_btn3;
    private javax.swing.JPanel southBody;
    private javax.swing.JPanel up;
    // End of variables declaration//GEN-END:variables
}
