/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

/**
 *
 * @author edwin
 */
public class PanelHabitacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelHabitacion
     */
    public PanelHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelIMG = new javax.swing.JPanel();
        lblIMG1 = new javax.swing.JLabel();
        lblIMG2 = new javax.swing.JLabel();
        lblIMG3 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();

        setBackground(new java.awt.Color(1, 74, 173));
        setLayout(new java.awt.BorderLayout());

        PanelIMG.setBackground(new java.awt.Color(255, 51, 51));
        PanelIMG.setPreferredSize(new java.awt.Dimension(300, 480));
        PanelIMG.setLayout(new java.awt.GridBagLayout());

        lblIMG1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 263;
        gridBagConstraints.ipady = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 292, 0);
        PanelIMG.add(lblIMG1, gridBagConstraints);

        lblIMG2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        PanelIMG.add(lblIMG2, gridBagConstraints);

        lblIMG3.setText("jLabel3");
        PanelIMG.add(lblIMG3, new java.awt.GridBagConstraints());

        add(PanelIMG, java.awt.BorderLayout.WEST);

        PanelInfo.setPreferredSize(new java.awt.Dimension(360, 480));

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        add(PanelInfo, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIMG;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JLabel lblIMG1;
    private javax.swing.JLabel lblIMG2;
    private javax.swing.JLabel lblIMG3;
    // End of variables declaration//GEN-END:variables
}
