/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import java.awt.BorderLayout;
import static java.awt.PageAttributes.MediaType.B;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author feriv
 */
public class B extends javax.swing.JPanel {

    /**
     * Creates new form B
     */
    public B() {
        initComponents();
    List<JPanel> ListaPaneles = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarrusel1 = new componentes.PanelCarrusel();

        setBackground(new java.awt.Color(1, 74, 173));
        setPreferredSize(new java.awt.Dimension(651, 472));

        panelCarrusel1.setForeground(new java.awt.Color(1, 74, 173));
        panelCarrusel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCarrusel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarrusel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarrusel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelCarrusel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCarrusel1MouseClicked
     
        B.add(Habitacion_1,BorderLayout.CENTER);
        
        Habitacion_1 Inicio= new Habitacion_1();
    }//GEN-LAST:event_panelCarrusel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.PanelCarrusel panelCarrusel1;
    // End of variables declaration//GEN-END:variables
}
