/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import java.awt.BorderLayout;
import static java.awt.PageAttributes.MediaType.B;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import modelo.vo.Habitacion;

/**
 *
 * @author feriv
 */
public class Panel_Reservacion_Carrucel_Usuario extends javax.swing.JPanel {

    /**
     * Creates new form B
     */
    public Panel_Reservacion_Carrucel_Usuario() {
        initComponents();
        List<Habitacion> ListaHabitacion = new ArrayList<>();
        for (Habitacion habitacion : ListaHabitacion) {
            PanelCarrusel.agregarPanel(new Habitacion_Panel(habitacion));
            //Hechenme paro al rato para que se actualize cada que agrego un panel de habitacion
            
        }
       
    }
    
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCarrusel = new componentes.PanelCarrusel();

        setBackground(new java.awt.Color(1, 74, 173));
        setPreferredSize(new java.awt.Dimension(651, 472));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCarrusel, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(PanelCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.PanelCarrusel PanelCarrusel;
    // End of variables declaration//GEN-END:variables
}
